### ISSUE TITLE
Fix improper error handling

### ISSUE THREAD

**Issue by alessioalex** [robertkowalski/get-license-npm#1]
https://github.com/robertkowalski/get-license-npm/blob/master/lib/index.js#L31

https://github.com/robertkowalski/get-license-npm/blob/master/lib/index.js#L66

By throwing inside of those async functions (instead of rejecting the promise or executing the callback early with the error parameter) you are basically crushing the Node process without giving the user the possibility to handle the error.

**Comment by robertkowalski** [comment]
oh! i thought the promise would just fail in those cases and the user could catch it with:

```js

getLicense()
  .then(() => { // yada yada ... })
  .catch(() => { // handle error })
```

**Comment by alessioalex** [comment]
Normally if you throw inside a Promise that works as you said, but in the two situations you're actually inside asynchronous functions (`async.parallel` and `fs.stat`) and I don't think that still applies.

Additionally you also provide a callback api (which I was using) and you also need to return the error there as well.

Will make a pull request soon.
